### ISSUE TITLE
media type name stability

### ISSUE THREAD

**Issue by dret** [inadarei/rfc-healthcheck#1]
as with the infamous `X-...` naming patterns for header fields (https://tools.ietf.org/html/rfc6648), the same applies to media types: assigning a name in the draft and then planning to change it is not the best strategy. pick a name you'd like to keep, and then stick to it. otherwise you build fragmentation into the development/adoption process, which makes it harder for people to understand which identifier to use.

**Comment by inadarei** [comment]
@dret, I have already submitted `application/vnd.health+json` to IANA for registration. 

Are you concerned that it is in the vendor branch and not something like `application/health+json`? I have zero experience applying for non-vendor branch and am quite terrified to even try it. Vendor branch usually takes 1-2month. 

I was feeling fine the media type to be application/vnd.health+json forever. 

Is that your concern?

**Comment by dret** [comment]
On 2018-01-16 12:29, Irakli Nadareishvili wrote:
> @dret <https://github.com/dret>, I have already submitted 
> |application/vnd.health+json| to IANA for registration.

i didn't know. that's early, but it is what it is.

> Are you concerned that it is in the vendor branch and not something like 
> |application/health+json|? I have zero experience applying for 
> non-vendor branch and am quite terrified to even try it. Vendor branch 
> usually takes 1-2month.

nope, that distinction is a bit artificial anyway. i am just concerned 
with identifier stability.

> I was feeling fine the media type to be application/vnd.health+json forever.
> Is that your concern?

ok. in that case the text warning about the identifier changing can be 
removed, right? aha, it seems like it is already gone...

**Comment by inadarei** [comment]
Fixed

**Comment by dret** [comment]
great, thanks!
