### ISSUE TITLE
observedUnit and connections

### ISSUE THREAD

**Issue by peteraritchie** [inadarei/rfc-healthcheck#31]
In the `cassandra:connections` there is an `observedValue` but no `observedUnit`.  If that's implied, what does a connection metric value of `75` signify?

**Comment by inadarei** [comment]
Number of connections. ObservedMetric is not necessary and is only used when the observation can be measured in multiple units (e.g. byte, kilobyte etc.). Number of connections can only be measured in one unit - the number of connections, so indicating a unit would be unnecessary.
