### ISSUE TITLE
Should this only detail the media type and content?

### ISSUE THREAD

**Issue by peteraritchie** [inadarei/rfc-healthcheck#32]
The RFC details "making an(sic) health check endpoint available"; but should this only be a description of the content, and not detail a unique endpoint?  e.g. to support:
```
GET /dbnode/dfd6cf2b HTTP/1.1
Host: api.example.com
Accept: application/health+json
User-Agent: MyHealthMonitor

```

**Comment by inadarei** [comment]
Yes, absolutely - the intent of the spec is to only document media type and the content. Anything else is for demonstration purposes only. Where do you feel we violate this intent?

**Comment by peteraritchie** [comment]
My mistake; I guess I read past "example". :)
