### ISSUE TITLE
Align example with defined specification

### ISSUE THREAD

**Issue by RRunner1337** [inadarei/rfc-healthcheck#38]
Specification defines usage of JSON attributes for example:

> 3.3.  releaseId
> 3.8.  serviceId

and defines usage of them in examples:
>   {
     "status": "pass",
     "version": "1",
     **"releaseID"**: "1.2.2",
     "notes": [""],
     "output": "",
     **"serviceID"**: "f03e522f-1f44-4062-9b55-9587f91c9c41",

As per my understanding JSON is case-sensitive and the example should reflect the specification.

**Comment by inadarei** [comment]
Fixed https://github.com/inadarei/rfc-healthcheck/pull/50
