### ISSUE TITLE
output in checks should also be omitted for healthy status

### ISSUE THREAD

**Issue by smoyer64** [inadarei/rfc-healthcheck#54]
In the [output](https://inadarei.github.io/rfc-healthcheck/#output-1) section of ``The Checks Object``, it should explicitly state that the field should be omitted for healthy status.  I'd propose the following change:

> output (optional) has the exact same meaning as the top-level “output” element, but for the sub-component/downstream dependency represented by the details object.  **This field SHOULD be omitted for “pass” states.**

**Comment by inadarei** [comment]
Agree. 13d90de
