### ISSUE TITLE
cassandra:connections[0] uses 'type' instead of 'componentType'

### ISSUE THREAD

**Issue by kalexmills** [inadarei/rfc-healthcheck#56]
It seems to be allowed to include unspecified keys (according to the use of `data` in other example checks) but according to the spec, `componentType` SHOULD be included whenever `componentId` is included, so this appears to be a typo.

Relevant snippet from `draft.md` included below.

```
    "cassandra:connections": [
      {
        "componentId": "dfd6cf2b-1b6e-4412-a0b8-f6f7797a60d2",
        "type": "datastore",
        "observedValue": 75,
        "status": "warn",
        "time": "2018-01-17T03:36:48Z",
        "output": "",
        "links": {
          "self": "http://api.example.com/dbnode/dfd6cf2b/health"
        }
      }
    ],
```

**Comment by inadarei** [comment]
Good catch. Thank you. Fixed in #6f2c8d9
