### ISSUE TITLE
"affectedEndpoints" field should be optional

### ISSUE THREAD

**Issue by smoyer64** [inadarei/rfc-healthcheck#66]
Currently, every other field in the checks object is optional.  As there are many types of sub-component that don't have ``affectedEndpoints``, it makes sense to mark this field as optional as well.

**Comment by inadarei** [comment]
Correct. This is fixed in the latest.

**Comment by smoyer64** [comment]
I should also have mentioned that the specification says that all or none of the fields may be used ... in any case, this change makes everything consistent.
